const _names = <String, String>{
  'notes': 'Notes',
  'nakedSingles': 'Naked Singles',
  'hiddenSingles': 'Hidden Singles',
  'hiddenSingleRow': 'Hidden Single (Row)',
  'hiddenSingleColumn': 'Hidden Single (Column)',
  'hiddenSingleBox': 'Hidden Single (Box)',
  'lockedCandidates': 'Locked Candidates',
  'lockedCandidatesPointingRow': 'Locked Candidates — Pointing (Row)',
  'lockedCandidatesPointingColumn': 'Locked Candidates — Pointing (Column)',
  'lockedCandidatesReductionRow': 'Locked Candidates — Reduction (Row)',
  'lockedCandidatesReductionColumn': 'Locked Candidates — Reduction (Column)',
  'nakedPairs': 'Naked Pairs',
  'nakedPairRow': 'Naked Pair (Row)',
  'nakedPairColumn': 'Naked Pair (Column)',
  'nakedPairBox': 'Naked Pair (Box)',
  'hiddenPairs': 'Hidden Pairs',
  'hiddenPairRow': 'Hidden Pair (Row)',
  'hiddenPairColumn': 'Hidden Pair (Column)',
  'hiddenPairBox': 'Hidden Pair (Box)',
  'nakedTriples': 'Naked Triples',
  'nakedTripleRow': 'Naked Triple (Row)',
  'nakedTripleColumn': 'Naked Triple (Column)',
  'nakedTripleBox': 'Naked Triple (Box)',
  'hiddenTriples': 'Hidden Triples',
  'hiddenTripleRow': 'Hidden Triple (Row)',
  'hiddenTripleColumn': 'Hidden Triple (Column)',
  'hiddenTripleBox': 'Hidden Triple (Box)',
  'nakedQuadruples': 'Naked Quadruples',
  'hiddenQuadruples': 'Hidden Quadruples',
  'xWing': 'X-Wing',
  'swordfish': 'Swordfish',
  'xyWing': 'XY-Wing',
  'xyzWing': 'XYZ-Wing',
  'forcedChains': 'Forced Chains',
};

String techniqueDisplayName(String id) => _names[id] ?? id;
