name: CI — Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  backend:
    name: Go — lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: cashapp/activate-hermit@e49f5cb4dd64ff0b0b659d1d8df499595451155a # v1
        with:
          cache: "true"
      - name: Run linter
        working-directory: backend
        run: golangci-lint run
      - name: Run tests
        working-directory: backend
        run: go test ./...
